"""add address_district column

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-10

Adds address_district to salons table for the area filter feature (DEC-010).
Written manually — NOT autogenerated — because the production DB has ~21 tables
not yet tracked by ORM models; autogenerate would attempt to DROP them.

address_region already existed in production; this migration adds only
address_district.
"""
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "salons",
        sa.Column(
            "address_district",
            sa.String(120),
            nullable=True,  # Nullable until T-003 backfill populates existing rows
        ),
    )
    op.create_index(
        "ix_salons_address_district",  # ix_ prefix follows SQLAlchemy naming convention
        "salons",
        ["address_district"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_salons_address_district", table_name="salons")
    op.drop_column("salons", "address_district")
